/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
//import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
         SearchAmazon sa = new SearchAmazon(); // Initialize your test class
        //TODO: call your test case functions one after other here
         sa.Search();
        //END Tests
         sa.endTest(); // End your test by clearning connections and closing browser
         
         CountHyperlinks ch=new CountHyperlinks();
         ch.countLinks();
         ch.endTest();

         ImageUrlsBookMyShow ibs=new ImageUrlsBookMyShow();
         ibs.imageUrl();
         ibs.endTest();

         PostOnLinkedin pl=new PostOnLinkedin();
         pl.post();
         pl.endTest();
         
         PostImageOnLinkedIN image=new PostImageOnLinkedIN();
         image.postImage();
         image.endTest();

         NestedFrame frame=new NestedFrame();
         frame.nested();
         frame.endTest();

         AlertPrompt alert=new AlertPrompt();
         alert.alerts();
         alert.endTest();

         IMDBRatings imdb=new IMDBRatings();
         imdb.imdb();
         imdb.endTest();

         WindowHandle winhandler=new WindowHandle();
         winhandler.windowhandletest();
         winhandler.endTest();

    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
